# netlify.toml
[build]
  # base = "subfolder"  # если проект не в корне, потом настроишь
  command = "npm run build"
  publish = "dist"      # или "build", если твой проект собирается в папку build
